apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret-company-com
  namespace: cert-manager
type: Opaque
stringData:
  api: "*************************************"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-company-com
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-company-com
    solvers:
      - selector: {}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret-company-com
              key: api

