# The port the API Server will be listening on.
kube_apiserver_ip: "{{ kube_service_addresses|ipaddr('net')|ipaddr(1)|ipaddr('address') }}"
kube_apiserver_port: 6443  # (https)
# kube_apiserver_insecure_port: 8080  # (http)
# Set to 0 to disable insecure port - Requires RBAC in authorization_modes and kube_api_anonymous_auth: true
kube_apiserver_insecure_port: 0  # (disabled)

kube_apiserver_request_timeout: 300s
kube_apiserver_pod_eviction_not_ready_timeout_seconds: "60" #300
kube_apiserver_pod_eviction_unreachable_timeout_seconds: "60" #300

# 1.10+ admission plugins
kube_apiserver_enable_admission_plugins:
  - NamespaceLifecycle # Запрещает удаление системных неймспейсов
  - DefaultIngressClass # Добавляет дефолтный ингресс класс
  - DenyServiceExternalIPs # Запрещает создавать Service c ExternalIP
  - NamespaceExists
  - ResourceQuota

# 1.10+ list of disabled admission plugins
#kube_apiserver_disable_admission_plugins: []

## Support tls cipher suites.
tls_cipher_suites:
 - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
 - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
 - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
 - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
 - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305